project: KarolsChecks
datadog_enabled: true
prometheus_enabled: true
#UNIQUE Jobnames!
up_jobs:
  bitgrip_up:
    description: 'Came for the money, stayed for the story'
    host: 'bitgrip.de'
    url: https://www.bitgrip.de/kontakt
    method: GET
    expected_code: 301
  auth_check:
    description: 'XXX'
    host: 'postman-echo.com'
    url: https://postman-echo.com/basic-auth
    method: GET
    headers:
      Authorization:
      - 'Basic cG9zdG1hbjpwYXNzd29yZA=='
dns_jobs:
  bitgrip_dns:
    host: 'occ-ci2.ksb.bitgrip.berlin'
    fqdn: 'occ-ci2.ksb.bitgrip.berlin'
    ips:
    - '116.203.116.72'
    - '159.69.202.97'
    - '159.69.25.18'
    - '159.69.33.100'
