####################################
# Documented instance parameters
###################################

#project: Big_Company                                ### Project Name, i.e. customer name
#up_jobs:                                            ### A list of UpJobs, tracking the status for given url
#  myUpJob:                                          ### Name of this job
#    host: 'google.com'                              ### Host of the url of this job (default: host retrieved from url)
#    url: https://www.google.de                      ### The URL to check
#    method: POST                                    ### The method used for the check (default: GET)
#    headers:                                        ### Headers for the request as map (string -> string)
#      Authorization: 'Basic abc=='
#      Content-Type: 'application/json'
#    plain_body: '{"code":"etanorm","count":15}'     ### The request body
#    base64_body: '{"code":"etanorm","count":15}'    ### Base64 encoded request body
#    expected_code: 301                              ### Expected response code of the check (default: 200)
#    content_match: '.*"totalResults" : 9'           ### Regular Expression to be found in response body (omitted when empty)
#    reverse_content_match: true                     ### Reverse behaviour of content_match logic (default: false)
#    check_ssl: true                                 ### Enables Validation of SSL certificates (default: true)
#    tags:                                           ### Add custom tags here, add a map (string ->String)
#      cloud_provider: azure
#      kube_cluster_name: ksb-az-stage
#      stage: stage
#    Oauth:
#      auth_url: www.auth.de                         ### https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
#      headers:
#        Accept: application/json                    ### headers for the auth server
#      params:                                       ### params sent to auth server
#        grant_type: client_credentials              ### working with client_credentials|password
#        client_id: ichbinclient
#        client_secret: password123
#        username: name
#        password: geheim
#
#
#dns_jobs:                                          ### A list of DNSJobs, tracking the status for given url
#  myDnsJob:                                        ### Name of this job
#    host: 'google.com'                             ### Host to perform the DNSJob on
#    fqdn: 'www.google.com'                         ### Fully qualified domain name
#    ips:                                           ### a list of expected ips
#      - '116.203.116.72'
#      - '159.69.202.97'
#      - '159.69.25.18'
#      - '159.69.33.100'
#    tags:                                          ### Add custom tags here, add a map (string -String)
#      cloud_provider: azure
#      kube_cluster_name: ksb-az-stage
#      stage: stage
