project: Big_Company
up_jobs:
  myUpJob:
    host: 'uptrack'
    url: https://www.google.com/

    Oauth:
      auth_url: https://preview-occ-ci2.ksb.bitgrip.berlin/authorizationserver/oauth/token
      headers:
        Accept: application/json
        Content-Type: application/x-www-form-urlencoded
      params:
        grant_type: client_credentials
        client_id: web_client
        client_secret: ksbweb1@stag
        username: ksbtestcustomer
        password: password1!
