project: KarolsChecks
base_url:
up_jobs:
  bitgrip_checker:
    description: 'Came for the money, stayed for the story'
    url_suffix: https://www.bitgrip.de/kontakt
    method: GET
    expected_code: 301
  AUTh_CHECK:
    description: 'XXX'
    url_suffix: https://postman-echo.com/basic-auth
    method: GET
    headers:
      Authorization:
      - 'Basic cG9zdG1hbjpwYXNzd29yZA=='

dns_jobs:
  bitgrip_dns_check:
    fqdn: 'occ-ci2.ksb.bitgrip.berlin'
    ips:
    - '116.203.116.72'
    - '159.69.202.97'
    - '159.69.25.18'
    - '159.69.33.100'
