log_json: false
verbosity: 1
uptrack:
  default_interval: 10
  jobs_config: './config/jobs.yaml'
  datadog:
    appKey: 'app'
    apiKey: 'api'
    interval: 5
  prometheus:
    port: 2222
    endpoint: /metrics
